name: 'Plugin Issue Bot'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: 'GitHub Token'
runs:
  using: 'node12'
  main: 'dist/index.js'
