name: 'Plugin Issue Bot'
on:
  push:
    branches:
      - main
  issues:
    types: [opened, edited]
  pull_request:
    types: [closed]

jobs:
  issue_bot_job:
    runs-on: ubuntu-latest
    name: issue bot
    steps:
      # 要使用此仓库的私有操作，
      # 您必须检出仓库
      - name: Checkout
        uses: actions/checkout@v2
      - name: issue
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
